# message = "weeeeeeeeeeeeeeeeeeeelcomemeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeessssssssssssssssaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaggggggggggggggggggggggggggggggggggggggggeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeettttttttttttttttttttttttttttttttttttttttttttttttttttttooooooooweeeeeeeeeeeeeeeeeeeelcomemeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeessssssssssssssssaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaggggggggggggggggggggggggggggggggggggggggeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeetttttttttttttttttttttttttttttttttttttttttttttttttttt"
# puts message.length
#
# message1 = "weeeeeeeeeeeeeeeeeeeelcomemeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeessssssssssssssssaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaggggggggggggggggggggggggggggggggggggggggeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeettttttttttttttttttttttttttttttttttttttttttttttttttttttoooooooo"
# puts message1.length
#
# message2 = "weeeeeeeeeeeeeeeweeeefedeeeeeeeeeeeeeeeelcomemeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeessssssssssssssssaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaggggggggggggggggggggggggggggggggggggggggeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeettttttttttttttttttttttttttttttttttttttttttttttttttttttooooooooeeeeelcomemeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeessssssssssssssssaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaggggggggggggggggggggggggggggggggggggggggeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeettttttttttttttttttttttttttttttttttttttttttttttttttttttoooooooo"
# puts message2.length

def computer_fingers
  rand(6)
end

computer_fingers1 = computer_fingers
puts "How many fingers am I holding out?"
user_guess = gets.chomp.to_i

puts "Computer had #{computer_fingers1} held out."
puts "You guessed right!" if  computer_fingers1 == user_guess